name: style-mimicry
channels:
  - nodefaults
  - rapidsai
  - conda-forge
  - nvidia
dependencies:
  - python=3.12
  - pip
  - peft
  - cuda-version=12.*
  - tensorflow>=2.10.0
  - cuml=26.2
  - numpy>=1.21.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - openpyxl>=3.0.0
  - tqdm>=4.60.0
  - bs4>=0.0.1
  - requests>=2.25.0
  - selenium>=4.0.0
  - webdriver-manager>=3.0.0
  - beautifulsoup4>=4.9.0
  - jinja2
  - colorama
  - pip:
      - -r mimicry/protections/tools/mist/requirements.txt

# to keep up to date with the latest conda version, run the following command in your terminal:
# conda update -n base -c conda-forge conda

# to create the environment, run the following command in your terminal:
# conda env create -f environment.yml

# to activate the environment, run the following command in your terminal:
# conda activate style-mimicry
